local_costmap:
  global_frame: /agv/map
  robot_base_frame: /base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.1
  transform_tolerance: 0.5
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   
     # robot radius set to min to pass near obstacles
  #inflation_radius: 0.060   
  inflation_radius: 0.015   
  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0

  inflation_layer:
    enabled: true
    cost_scaling_factor: 0.0 # the lower, the more cost
    inflation_radius: 0.1    # big values make it harder to pass through narrow spaces
