agv:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint_wheel_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_2
    pid: {p: 100.0, i: 0.01, d: 10.0}  
  joint_wheel_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_4
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_5
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_6
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_7_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_7
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_8_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_8
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_1_dir_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_1_dir
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_2_dir_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_2_dir
    pid: {p: 100.0, i: 0.01, d: 10.0}  
  joint_wheel_3_dir_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_3_dir
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_4_dir_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_4_dir
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_5_dir_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_5_dir
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_6_dir_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_6_dir
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_7_dir_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_7_dir
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_wheel_8_dir_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_8_dir
    pid: {p: 100.0, i: 0.01, d: 10.0}
